{{/*
Copyright National Payments Corporation of India. All Rights Reserved.
SPDX-License-Identifier:  GPL-3.0
*/}}

{{- if eq "chaincode_ops" .Values.job_type }}
{{- if .Values.fabric_actions.update_anchor_peer }}

{{ $BankName     := .Values.nameOverride }}
{{ $HlfDomain    := .Values.hlf_domain }}
{{ $ChannelName  := .Values.channel_name }}

{{- range .Values.identities }}
{{- if eq "peer" .identity_type }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "fabric-ops.fullname" $ }}-rev-{{ $.Release.Revision }}
  labels:
    {{- include "fabric-ops.labels" $ | nindent 4 }}
spec:
  template:
    metadata:
      {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fabric-ops.selectorLabels" $ | nindent 8 }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fabric-ops.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      restartPolicy: Never
      initContainers:
      containers:
        - name: cli
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          workingDir: {{ $.Values.workdir }}/peer
          command: ["/bin/sh","-c"]
          args:
           - /scripts/fabric_enroll.sh;
             /scripts/fabric_update_anchorpeer.sh;
          tty: true
          env: 
            - name: CLUSTER_DOMAIN
              value: {{ $HlfDomain }}
            - name: FABRIC_LOGGING_SPEC
              value: INFO
            - name: CORE_PEER_ADDRESS
              value: {{ .identity_name }}:{{ $.Values.peer_internal_service_port }}
            - name: CORE_PEER_ID
              value: cli-{{ $BankName }}
            - name: CORE_PEER_LOCALMSPID
              value: {{ $BankName }}
            - name: CORE_PEER_MSPCONFIGPATH
              value: {{ $.Values.workdir }}/peer/crypto/users/admin/msp
            - name: CORE_PEER_TLS_CERT_FILE
              value: {{ $.Values.workdir }}/peer/crypto/users/{{ .identity_name }}/tls/server.crt
            - name: CORE_PEER_TLS_ENABLED
              value: "true"
            - name: CORE_PEER_TLS_KEY_FILE
              value: {{ $.Values.workdir }}/peer/crypto/users/{{ .identity_name }}/tls/server.key
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: {{ $.Values.workdir }}/peer/crypto/users/{{ .identity_name }}/tls/ca.crt
            - name: GOPATH
              value: /opt/gopath
            - name: ORDERER_CA
              value: {{ $.Values.workdir }}/peer/orderer-crypto/orderer/tlsca/ca-cert.pem
            - name: ORDERER_BASE_PATH
              value: {{ $.Values.workdir }}/peer/orderer-crypto/orderer/tlsca
            - name: IDENTITY_NAME
              value: {{ .identity_name }}
          volumeMounts:
            - name: fabric-ops
              subPath: config.yaml
              mountPath: /tmp/config.yaml
            - name: fabric-ops
              subPath: fabric_enroll.sh
              mountPath: /scripts/fabric_enroll.sh
            - name: fabric-ops
              subPath: fabric_update_anchorpeer.sh
              mountPath: /scripts/fabric_update_anchorpeer.sh
            - name: fabric-ops
              subPath: anchorpeer.json
              mountPath: {{ $.Values.workdir }}/peer/anchorpeer.json
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
      volumes:
        - name: fabric-ops
          configMap:
            name: {{ include "fabric-ops.fullname" $ }}
            defaultMode: 0777
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}