{{/*
Copyright National Payments Corporation of India. All Rights Reserved.
SPDX-License-Identifier:  GPL-3.0
*/}}

{{- $Chart               := .Chart.Name -}}
{{- $Name                := .Values.nameOverride | default .Chart.Name -}}
{{- $Annotations         := and .Values.global .Values.global.ingress .Values.global.ingress.annotations -}}
{{- $ClassName           := and .Values.global .Values.global.ingress .Values.global.ingress.className -}}
{{- $IngressEnabled      := and .Values.global .Values.global.ingressEnabled -}}
{{- $useDefaultDNS       := or .Values.useDefaultServiceDNS (and .Values.global .Values.global.useDefaultServiceDNS) }}

{{- range .Values.orderers }}
{{- $ordererUseDefaultDNS := or .useDefaultServiceDNS $useDefaultDNS }}
{{- if or (and $IngressEnabled (ne .ingressEnabled false) (not (and $ordererUseDefaultDNS (not .ingressEnabled)))) (eq .ingressEnabled true) }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}-{{ include "fabric-orderer.fullname" $ }}
  labels:
    app: {{ include "fabric-orderer.fullname" $ }}-{{ .name }}
    {{- include "fabric-orderer.labels" $ | nindent 4 }}
    {{- if .additionalLabels -}}
    {{ toYaml .additionalLabels | nindent 4 }}
    {{- end }}
  {{- with $Annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ $ClassName }}
  rules:
    - host: {{ .identity_name }}.{{ .hlf_domain | default $.Values.hlf_domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .name }}-{{ include "fabric-orderer.fullname" $ }}
                port:
                  number: {{ .servicePort | default $.Values.global.servicePort }}
{{- end }}
{{- end }}
