apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-filestore
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/test"
