{{- $root := . -}}
{{- $tlsRootCA := include "yugabyte.tlsRootCA" (dict "root" $root) | fromYaml -}}
---
{{- if $root.Values.tls.certManager.enabled }}
{{- if $root.Values.tls.certManager.bootstrapSelfsigned }}
---
{{ $appLabelArgs := dict "label" "yugabyte" "root" $root }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name:  {{ (printf "%s-bootstrap" (include "yugabyte.tls_cm_issuer" $root)) | quote }}
  namespace: "{{ $root.Release.Namespace }}"
  labels:
    {{- include "yugabyte.applabel" ($appLabelArgs) | indent 4 }}
    {{- include "yugabyte.labels" $root | indent 4 }}
spec:
  selfSigned: {}
---
{{ $appLabelArgs := dict "label" "yugabyte" "root" $root }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $root.Values.oldNamingStyle | ternary "yugabyte-ca" (printf "%s-ca" (include "yugabyte.fullname" $root)) }}
  namespace: "{{ $root.Release.Namespace }}"
  labels:
    {{- include "yugabyte.applabel" ($appLabelArgs) | indent 4 }}
    {{- include "yugabyte.labels" $root | indent 4 }}
spec:
  isCA: true
  privateKey:
    algorithm: {{ $root.Values.tls.certManager.certificates.algorithm | quote }}
    encoding: PKCS8
    size: {{ $root.Values.tls.certManager.certificates.keySize }}
  commonName: Yugabyte Selfsigned CA
  secretName: {{ $root.Values.oldNamingStyle | ternary "yugabyte-ca" (printf "%s-ca" (include "yugabyte.fullname" $root)) }}
  issuerRef:
    name: {{ (printf "%s-bootstrap" (include "yugabyte.tls_cm_issuer" $root)) | quote }}
    kind: Issuer
---
{{ $appLabelArgs := dict "label" "yugabyte" "root" $root }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "yugabyte.tls_cm_issuer" $root | quote }}
  namespace: "{{ $root.Release.Namespace }}"
  labels:
    {{- include "yugabyte.applabel" ($appLabelArgs) | indent 4 }}
    {{- include "yugabyte.labels" $root | indent 4 }}
spec:
  ca:
    secretName: {{ $root.Values.oldNamingStyle | ternary "yugabyte-ca" (printf "%s-ca" (include "yugabyte.fullname" $root)) }}
---
{{- else }}
{{/* when bootstrapSelfsigned = false, ie. when using an external CA.
Create a Secret with just the rootCA.cert value and mount into master/tserver pods.
This will be used as a fall back in case the Secret generated by cert-manager does not
have a root ca.crt. This can happen for certain certificate issuers like LetsEncrypt.
*/}}
---
{{ $appLabelArgs := dict "label" "yugabyte" "root" $root }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-root-ca" (include "yugabyte.fullname" $root) }}
  namespace: "{{ $root.Release.Namespace }}"
  labels:
    {{- include "yugabyte.applabel" ($appLabelArgs) | indent 4 }}
    {{- include "yugabyte.labels" $root | indent 4 }}
type: Opaque
data:
  ca.crt: {{ $tlsRootCA.cert }}
  {{/* if useExistingServerCertificate is true, then tls.crt and tls.key will not be set */}}
  {{if $root.Values.tls.certManager.useExistingServerCertificate -}}
  tls.crt: ""
  tls.key: ""
  {{- end }}
---
{{- end }}


{{/*
The below Certificate resource will trigger cert-manager to issue crt/key into Secrets.
These secrets are mounted into master/tserver pods.
*/}}
{{- range .Values.Services }}
{{- $service := . -}}
{{- $appLabelArgs := dict "label" .label "root" $root -}}
{{- $serviceValues := (dict "Service" $service "Values" $root.Values "Chart" $root.Chart "Release" $root.Release) -}}
{{- $vars := include "yugabyte.stsIndexVars" (dict "serviceName" .name "root" $root) | fromYaml -}}
{{- range $stsIdx := until (int $vars.stsCount) }}
{{- $loopVars := include "yugabyte.stsIndexLoopVars" (dict "stsIdx" $stsIdx "stsStart" $vars.stsStart "stsEnd" $vars.stsEnd "replicas" $vars.replicas "moveOpReplicas" $vars.moveOpReplicas) | fromYaml -}}
{{- $currentStsIndex := $loopVars.currentStsIndex -}}
{{- $useMoveOp := $loopVars.useMoveOp -}}
{{- $stsIndexSuffix := $loopVars.stsIndexSuffix -}}
{{- $currentReplicas := $loopVars.currentReplicas }}
{{- if gt (int $currentReplicas) 0 }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $root.Values.oldNamingStyle | ternary (printf "%s%s-yugabyte-tls-cert" $service.label $stsIndexSuffix) (printf "%s-%s%s-tls-cert" (include "yugabyte.fullname" $root) $service.label $stsIndexSuffix) }}
  namespace: "{{ $root.Release.Namespace }}"
  labels:
    {{- include "yugabyte.applabel" ($appLabelArgs) | indent 4 }}
    {{- include "yugabyte.labels" $root | indent 4 }}
spec:
  secretTemplate:
    labels:
      {{- include "yugabyte.applabel" ($appLabelArgs) | indent 6 }}
      {{- include "yugabyte.labels" $root | indent 6 }}
  issuerRef:
    name: {{ include "yugabyte.tls_cm_issuer" $root | quote }}
    kind: {{ include "yugabyte.tls_issuer_kind" $root }}
    group: {{ include "yugabyte.tls_issuer_group" $root }}
  secretName: {{ $root.Values.oldNamingStyle | ternary (printf "%s%s-yugabyte-tls-cert" $service.label $stsIndexSuffix) (printf "%s-%s%s-tls-cert" (include "yugabyte.fullname" $root) $service.label $stsIndexSuffix) }}
  duration: {{ $root.Values.tls.certManager.certificates.duration | quote }}
  renewBefore: {{ $root.Values.tls.certManager.certificates.renewBefore | quote }}
  isCA: false
  privateKey:
    algorithm: {{ $root.Values.tls.certManager.certificates.algorithm | quote }}
    encoding: PKCS8
    size: {{ $root.Values.tls.certManager.certificates.keySize }}
    rotationPolicy: Always
  usages:
    - server auth
    - client auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
  {{- range $index := until ( int ( $currentReplicas ) ) }}
  {{- $nodeOldStyle := printf "%s%s-%d.%s.%s.svc.%s" $service.label $stsIndexSuffix $index $service.name $root.Release.Namespace $root.Values.domainName }}
  {{- $nodeNewStyle := printf "%s-%s%s-%d.%s-%s.%s.svc.%s" (include "yugabyte.fullname" $root) $service.label $stsIndexSuffix $index (include "yugabyte.fullname" $root) $service.name $root.Release.Namespace $root.Values.domainName }}

  {{- if $root.Values.multicluster.createServiceExports -}}
    {{- $nodeOldStyle = printf "%s%s-%d.%s.%s.%s.svc.clusterset.local" $service.label $stsIndexSuffix $index $root.Values.multicluster.kubernetesClusterId $service.name $root.Release.Namespace }}
    {{- $nodeNewStyle = printf "%s-%s%s-%d.%s.%s-%s.%s.svc.clusterset.local" (include "yugabyte.fullname" $root) $service.label $stsIndexSuffix $index $root.Values.multicluster.kubernetesClusterId (include "yugabyte.fullname" $root) $service.name $root.Release.Namespace }}
  {{- end -}}

  {{- if $root.Values.multicluster.createServicePerPod -}}
    {{- $nodeOldStyle = printf "%s%s-%d.%s.svc.%s" $service.label $stsIndexSuffix $index $root.Release.Namespace $root.Values.domainName }}
    {{- $nodeNewStyle = printf "%s-%s%s-%d.%s.svc.%s" (include "yugabyte.fullname" $root) $service.label $stsIndexSuffix $index $root.Release.Namespace $root.Values.domainName }}
  {{- end -}}
  {{- $node := $root.Values.oldNamingStyle | ternary $nodeOldStyle $nodeNewStyle }}
  - {{$node}}
  {{- end }}
  - {{ printf "%s-%s%s.%s.svc.%s" (include "yugabyte.fullname" $root) $service.name $stsIndexSuffix $root.Release.Namespace $root.Values.domainName }}
  uris: []
  ipAddresses: []
  {{- if $root.Values.tls.certManager.certificates.commonNameRequired }}
  commonName: {{ include "yugabyte.commonNameWithSuffix" (dict "commonName" ($root.Values.oldNamingStyle | ternary $service.name (printf "%s-%s" (include "yugabyte.fullname" $root) $service.name)) "root" $root) | quote }}
  {{- end }}
---
{{- end }}
{{- end }}
{{- end }}

---
{{ $appLabelArgs := dict "label" "yugabyte" "root" $root }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $root.Values.oldNamingStyle | ternary "yugabyte-tls-client-cert" (printf "%s-client-tls" (include "yugabyte.fullname" $root)) }}
  namespace: "{{ $root.Release.Namespace }}"
  labels:
    {{- include "yugabyte.applabel" ($appLabelArgs) | indent 4 }}
    {{- include "yugabyte.labels" $root | indent 4 }}
spec:
  secretTemplate:
    labels:
      {{- include "yugabyte.applabel" ($appLabelArgs) | indent 6 }}
      {{- include "yugabyte.labels" $root | indent 6 }}
  issuerRef:
    name: {{ include "yugabyte.tls_cm_issuer" $root | quote }}
    kind: {{ include "yugabyte.tls_issuer_kind" $root }}
    group: {{ include "yugabyte.tls_issuer_group" $root }}
  secretName:  {{ $root.Values.oldNamingStyle | ternary "yugabyte-tls-client-cert" (printf "%s-client-tls" (include "yugabyte.fullname" $root)) }}
  duration: {{ $root.Values.tls.certManager.certificates.duration | quote }}
  renewBefore: {{ $root.Values.tls.certManager.certificates.renewBefore | quote }}
  commonName: {{ include "yugabyte.commonNameWithSuffix" (dict "commonName" "yugabyte" "root" $root) | quote }}
  isCA: false
  privateKey:
    algorithm: {{ $root.Values.tls.certManager.certificates.algorithm | quote }}
    encoding: PKCS8
    size: {{ $root.Values.tls.certManager.certificates.keySize }}
    rotationPolicy: Always
  usages:
    - client auth
  dnsNames: []
  uris: []
  ipAddresses: []
---
{{- end }}
