{{- $root := . -}}
{{- range $service := $root.Values.Services }}
{{- if eq $service.name "yb-masters" }}
{{- $serviceValues := (dict "Service" $service "Values" $root.Values "Chart" $root.Chart "Release" $root.Release) -}}
{{- $appLabelArgs := dict "label" $service.label "root" $root -}}
{{- $vars := include "yugabyte.stsIndexVars" (dict "serviceName" $service.name "root" $root) | fromYaml -}}

{{- range $stsIdx := until (int $vars.stsCount) }}
{{- $loopVars := include "yugabyte.stsIndexLoopVars" (dict "stsIdx" $stsIdx "stsStart" $vars.stsStart "stsEnd" $vars.stsEnd "replicas" $vars.replicas "moveOpReplicas" $vars.moveOpReplicas) | fromYaml -}}
{{- $currentStsIndex := $loopVars.currentStsIndex -}}
{{- $useMoveOp := $loopVars.useMoveOp -}}
{{- $stsIndexSuffix := $loopVars.stsIndexSuffix -}}
{{- $storageInfo := $useMoveOp | ternary $root.Values.moveOp.storage.master $root.Values.storage.master -}}
{{- $storageEphemeral := $useMoveOp | ternary $root.Values.moveOp.storage.ephemeral $root.Values.storage.ephemeral -}}
{{- $currentReplicas := $loopVars.currentReplicas }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s%s-master-gflags" (include "yugabyte.fullname" $root) $stsIndexSuffix }}
  namespace: "{{ $root.Release.Namespace }}"
  labels:
    {{- include "yugabyte.applabel" ($appLabelArgs) | indent 4 }}
    {{- include "yugabyte.labels" $root | indent 4 }}
type: Opaque
stringData:
  server.conf.template: |
{{- if not $storageEphemeral }}
    --fs_data_dirs={{ template "yugabyte.fs_data_dirs" $storageInfo }}
{{- else }}
    --fs_data_dirs=/var/yugabyte
{{- end }}
{{- if eq $root.Values.ip_version_support "v6_only" }}
    --net_address_filter=ipv6_external,ipv6_non_link_local,ipv6_all,ipv4_external,ipv4_all
{{- end }}
{{- $masterCount := ternary $root.Values.replicas.totalMasters $currentReplicas $root.Values.isMultiAz }}
    --replication_factor={{ $masterCount }}
{{- if $root.Values.masterAddresses }}
    --master_addresses={{ $root.Values.masterAddresses }}
{{- else }}
    --master_addresses={{ include "yugabyte.master_addresses" (dict "root" $root "vars" $vars) }}
{{- end }}
{{- if not $root.Values.disableYsql }}
    --enable_ysql=true
{{- else }}
    --enable_ysql=false
{{- end }}
{{- if $root.Values.tls.enabled }}
    --certs_dir=/opt/certs/yugabyte
    --use_node_to_node_encryption={{ $root.Values.tls.nodeToNode }}
    --allow_insecure_connections={{ $root.Values.tls.insecure }}
{{- end }}
{{- if $root.Values.yugabytedUi.enabled }}
    --master_enable_metrics_snapshotter={{ $root.Values.yugabytedUi.metricsSnapshotter.enabled }}
    --metrics_snapshotter_tserver_metrics_whitelist={{ join "," $root.Values.yugabytedUi.metricsSnapshotter.whitelist }}
{{- end }}
    --metric_node_name=${EXPORTED_INSTANCE}
    --memory_limit_hard_bytes={{ template "yugabyte.memory_hard_limit" dict "size" $root.Values.resource.master.limits.memory "limitPercent" $root.Values.master.memoryLimitHardPercentage }}
    --stderrthreshold=0
    --num_cpus={{ ceil $root.Values.resource.master.requests.cpu }}
    --max_log_size=256
    --undefok=num_cpus,enable_ysql
    --use_node_hostname_for_local_tserver=true
    --rpc_bind_addresses={{ include "yugabyte.rpc_bind_address" $serviceValues }}
    --server_broadcast_addresses={{ include "yugabyte.server_broadcast_address" $serviceValues }}
    --webserver_interface={{ include "yugabyte.webserver_interface" $serviceValues }}
{{- range $flag, $override := $root.Values.gflags.master }}
    --{{ $flag }}={{ $override }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
---
