{{- $root := . -}}
{{- range $service := $root.Values.Services }}
{{- if eq $service.name "yb-tservers" }}
{{- $serviceValues := (dict "Service" $service "Values" $root.Values "Chart" $root.Chart "Release" $root.Release) -}}
{{- $appLabelArgs := dict "label" $service.label "root" $root -}}
{{- $vars := include "yugabyte.stsIndexVars" (dict "serviceName" $service.name "root" $root) | fromYaml -}}
{{- $masterStsVars := include "yugabyte.stsIndexVars" (dict "serviceName" "yb-masters" "root" $root) | fromYaml -}}

{{- range $stsIdx := until (int $vars.stsCount) }}
{{- $loopVars := include "yugabyte.stsIndexLoopVars" (dict "stsIdx" $stsIdx "stsStart" $vars.stsStart "stsEnd" $vars.stsEnd "replicas" $vars.replicas "moveOpReplicas" $vars.moveOpReplicas) | fromYaml -}}
{{- $currentStsIndex := $loopVars.currentStsIndex -}}
{{- $useMoveOp := $loopVars.useMoveOp -}}
{{- $stsIndexSuffix := $loopVars.stsIndexSuffix -}}
{{- $storageInfo := $useMoveOp | ternary $root.Values.moveOp.storage.tserver $root.Values.storage.tserver -}}
{{- $storageEphemeral := $useMoveOp | ternary $root.Values.moveOp.storage.ephemeral $root.Values.storage.ephemeral }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s%s-tserver-gflags" (include "yugabyte.fullname" $root) $stsIndexSuffix }}
  namespace: "{{ $root.Release.Namespace }}"
  labels:
    {{- include "yugabyte.applabel" ($appLabelArgs) | indent 4 }}
    {{- include "yugabyte.labels" $root | indent 4 }}
type: Opaque
stringData:
  server.conf.template: |
{{- if not $storageEphemeral }}
    --fs_data_dirs={{ template "yugabyte.fs_data_dirs" $storageInfo }}
{{- else }}
    --fs_data_dirs=/var/yugabyte
{{- end }}
{{- if eq $root.Values.ip_version_support "v6_only" }}
    --net_address_filter=ipv6_external,ipv6_non_link_local,ipv6_all,ipv4_external,ipv4_all
{{- end }}
{{- if $root.Values.masterAddresses }}
    --tserver_master_addrs={{ $root.Values.masterAddresses }}
{{- else }}
    --tserver_master_addrs={{ include "yugabyte.master_addresses" (dict "root" $root "vars" $masterStsVars) }}
{{- end }}
{{- if or $root.Values.authCredentials.ysql.password $root.Values.authCredentials.ysql.passwordSecretName }}
    --ysql_enable_auth=true
  {{- if (include "yugabyte.tserver.readinessProbe" $root) }}
    --ysql_hba_conf_csv="local all yugabyte trust"
  {{- end }}
{{- end }}
{{- if or $root.Values.authCredentials.ycql.user $root.Values.authCredentials.ycql.password $root.Values.authCredentials.ycql.passwordSecretName }}
    --use_cassandra_authentication=true
{{- end }}
{{- if $root.Values.tls.enabled }}
    --certs_dir=/opt/certs/yugabyte
    --use_node_to_node_encryption={{ $root.Values.tls.nodeToNode }}
    --allow_insecure_connections={{ $root.Values.tls.insecure }}
    --use_client_to_server_encryption={{ $root.Values.tls.clientToServer }}
    --certs_for_client_dir=/opt/certs/yugabyte
  {{- if $root.Values.tserver.serverBroadcastAddress }}
    --cert_node_filename={{ include "yugabyte.server_fqdn" $serviceValues }}
  {{- end }}
{{- end }}
{{- if not $root.Values.disableYsql }}
    --enable_ysql=true
    --pgsql_proxy_bind_address={{ include "yugabyte.pgsql_proxy_bind_address" $serviceValues }}
{{- else }}
    --enable_ysql=false
{{- end }}
{{- if $root.Values.yugabytedUi.enabled }}
    --tserver_enable_metrics_snapshotter={{ $root.Values.yugabytedUi.metricsSnapshotter.enabled }}
    --metrics_snapshotter_interval_ms={{ $root.Values.yugabytedUi.metricsSnapshotter.interval }}
    --metrics_snapshotter_tserver_metrics_whitelist={{ join "," $root.Values.yugabytedUi.metricsSnapshotter.whitelist }}
{{- end }}
    --metric_node_name=${EXPORTED_INSTANCE}
    --memory_limit_hard_bytes={{ template "yugabyte.memory_hard_limit" dict "size" $root.Values.resource.tserver.limits.memory "limitPercent" $root.Values.tserver.memoryLimitHardPercentage }}
    --stderrthreshold=0
    --max_log_size=256
    --num_cpus={{ ceil $root.Values.resource.tserver.requests.cpu }}
    --undefok=num_cpus,enable_ysql
    --use_node_hostname_for_local_tserver=true
    --cql_proxy_bind_address={{ include "yugabyte.cql_proxy_bind_address" $serviceValues }}
    --rpc_bind_addresses={{ include "yugabyte.rpc_bind_address" $serviceValues }}
    --server_broadcast_addresses={{ $root.Values.tserver.serverBroadcastAddress | default (include "yugabyte.server_broadcast_address" $serviceValues) }}
    --webserver_interface={{ include "yugabyte.webserver_interface" $serviceValues }}
{{- range $flag, $override := $root.Values.gflags.tserver }}
    --{{ $flag }}={{ $override }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
---
