{{/*
Copyright National Payments Corporation of India. All Rights Reserved.
SPDX-License-Identifier:  GPL-3.0
*/}}

{{- $Chart               := .Chart.Name -}}
{{- $Name                := .Values.nameOverride | default .Chart.Name -}}
{{- $Annotations         := and .Values.global .Values.global.ingress .Values.global.ingress.annotations -}}
{{- $ClassName           := and .Values.global .Values.global.ingressClass -}}
{{- $IngressEnabled      := and .Values.global .Values.global.ingressEnabled -}}
{{- $useDefaultDNS       := or .Values.useDefaultServiceDNS (and .Values.global .Values.global.useDefaultServiceDNS) }}

{{- range .Values.peers }}
{{- $peerUseDefaultDNS := or .useDefaultServiceDNS $useDefaultDNS }}
{{- if or (and $IngressEnabled (ne .ingressEnabled false) (not (and $peerUseDefaultDNS (not .ingressEnabled)))) (eq .ingressEnabled true) }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}-{{ include "fabric-peer.name" $ }}
  labels:
    app: {{ include "fabric-peer.name" $ }}
    {{- include "fabric-peer.labels" $ | nindent 4 }}
    {{- if .additionalLabels -}}
    {{ toYaml .additionalLabels | nindent 4 }}
    {{- end }}
  {{- with $Annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .ingressClass | default $ClassName }}
  rules:
    - host: {{ .name }}-{{ include "fabric-peer.name" $ }}.{{ $.Values.global.hlf_domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .name }}-{{ include "fabric-peer.name" $ }}
                port:
                  number: {{ .peerServicePort | default $.Values.global.peerServicePort }}
{{- end }}
{{- end }}